In [60]:
import pandas as pd
from glob import glob
import numpy as np
import os
import json

In [61]:
root = "/media/yesindeed/DATADRIVE1/mount/remote_cse/datasets/OmniMedVQA"

data_all = []

for dataset_file in glob(os.path.join(root, "QA_information", "Open-access", "*.json")):
    dataset = os.path.basename(dataset_file)[:-5]

    with open(dataset_file) as fp:
        data = json.load(fp)

    data_all.extend(data)

data_all

[{'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0000',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to obtain this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im553_g_ACRIMA.png',
  'option_A': 'PET scan',
  'option_B': 'CT scan',
  'option_C': 'Blood test',
  'option_D': 'Fundus imaging',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0001',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im351_g_ACRIMA.png',
  'option_A': 'Biopsy',
  'option_B': 'CT scan',
  'option_C': 'Colonoscopy',
  'option_D': 'Fundus imaging',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0002',
  'question_type': 'Modality Recognition',
  'question': 'What method was employed to obtain this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im702_g_ACRIMA.png',
  'option_A': 'MRI',
  'option_B': 'Biopsy',
  'option_C': 'Fundus imaging',
  'option_D': 'Electrocardiogram (ECG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0003',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im316_g_ACRIMA.png',
  'option_A': 'PET scan',
  'option_B': 'X-ray',
  'option_C': 'Fundus imaging',
  'option_D': 'Biopsy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0004',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was used to capture this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im041_ACRIMA.png',
  'option_A': 'CT scan',
  'option_B': 'Colonoscopy',
  'option_C': 'Fundus imaging',
  'option_D': 'Electrocardiogram (ECG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0005',
  'question_type': 'Modality Recognition',
  'question': 'What technique was employed for the acquisition of this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im598_g_ACRIMA.png',
  'option_A': 'MRI',
  'option_B': 'Colonoscopy',
  'option_C': 'Fundus imaging',
  'option_D': 'X-ray',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0006',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to acquire this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im671_g_ACRIMA.png',
  'option_A': 'X-ray',
  'option_B': 'CT scan',
  'option_C': 'Fundus imaging',
  'option_D': 'MRI',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0007',
  'question_type': 'Modality Recognition',
  'question': 'What method was utilized to acquire this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im539_g_ACRIMA.png',
  'option_A': 'Electroencephalogram (EEG)',
  'option_B': 'X-ray',
  'option_C': 'Fundus imaging',
  'option_D': 'Biopsy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0008',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im482_g_ACRIMA.png',
  'option_A': 'Electroencephalogram (EEG)',
  'option_B': 'Ultrasound',
  'option_C': 'Fundus imaging',
  'option_D': 'MRI',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0009',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to acquire this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im230_ACRIMA.png',
  'option_A': 'Ultrasound',
  'option_B': 'Electrocardiogram (ECG)',
  'option_C': 'Fundus imaging',
  'option_D': 'PET scan',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0010',
  'question_type': 'Modality Recognition',
  'question': 'What was the imaging technique employed to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im514_g_ACRIMA.png',
  'option_A': 'PET scan',
  'option_B': 'Fundus imaging',
  'option_C': 'MRI',
  'option_D': 'Ultrasound',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0011',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im366_g_ACRIMA.png',
  'option_A': 'Ultrasound',
  'option_B': 'Blood test',
  'option_C': 'Fundus imaging',
  'option_D': 'Electroencephalogram (EEG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0012',
  'question_type': 'Modality Recognition',
  'question': 'What technique was utilized for obtaining this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im104_ACRIMA.png',
  'option_A': 'Colonoscopy',
  'option_B': 'Electroencephalogram (EEG)',
  'option_C': 'Electrocardiogram (ECG)',
  'option_D': 'Fundus imaging',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0013',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im223_ACRIMA.png',
  'option_A': 'X-ray',
  'option_B': 'Fundus imaging',
  'option_C': 'Biopsy',
  'option_D': 'PET scan',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0014',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to capture this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im590_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'Electrocardiogram (ECG)',
  'option_C': 'Electroencephalogram (EEG)',
  'option_D': 'Ultrasound',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0015',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to obtain this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im302_ACRIMA.png',
  'option_A': 'Ultrasound',
  'option_B': 'Electrocardiogram (ECG)',
  'option_C': 'MRI',
  'option_D': 'Fundus imaging',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0016',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im454_g_ACRIMA.png',
  'option_A': 'X-ray',
  'option_B': 'CT scan',
  'option_C': 'Fundus imaging',
  'option_D': 'MRI',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0017',
  'question_type': 'Modality Recognition',
  'question': 'What was the imaging technique used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im464_g_ACRIMA.png',
  'option_A': 'Colonoscopy',
  'option_B': 'Fundus imaging',
  'option_C': 'PET scan',
  'option_D': 'Electroencephalogram (EEG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0018',
  'question_type': 'Modality Recognition',
  'question': 'What imaging modality was utilized to capture this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im390_g_ACRIMA.png',
  'option_A': 'Biopsy',
  'option_B': 'PET scan',
  'option_C': 'Fundus imaging',
  'option_D': 'X-ray',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0019',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was utilized to obtain this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im171_ACRIMA.png',
  'option_A': 'CT scan',
  'option_B': 'Electrocardiogram (ECG)',
  'option_C': 'Fundus imaging',
  'option_D': 'Biopsy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0020',
  'question_type': 'Modality Recognition',
  'question': 'What imaging modality was utilized to capture this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im621_g_ACRIMA.png',
  'option_A': 'Biopsy',
  'option_B': 'Electrocardiogram (ECG)',
  'option_C': 'Fundus imaging',
  'option_D': 'Colonoscopy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0021',
  'question_type': 'Modality Recognition',
  'question': 'What method was utilized to obtain this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im069_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'PET scan',
  'option_C': 'Biopsy',
  'option_D': 'MRI',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0022',
  'question_type': 'Modality Recognition',
  'question': 'What method was utilized to acquire this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im478_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'Biopsy',
  'option_C': 'Electroencephalogram (EEG)',
  'option_D': 'Electrocardiogram (ECG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0023',
  'question_type': 'Modality Recognition',
  'question': 'What method was utilized to acquire this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im704_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'MRI',
  'option_C': 'PET scan',
  'option_D': 'Colonoscopy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0024',
  'question_type': 'Modality Recognition',
  'question': 'What method was utilized to obtain this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im480_g_ACRIMA.png',
  'option_A': 'PET scan',
  'option_B': 'CT scan',
  'option_C': 'Fundus imaging',
  'option_D': 'Colonoscopy',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0025',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to obtain this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im641_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'CT scan',
  'option_C': 'Electroencephalogram (EEG)',
  'option_D': 'X-ray',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0026',
  'question_type': 'Modality Recognition',
  'question': 'Which imaging modality was utilized to acquire this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im338_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'Electroencephalogram (EEG)',
  'option_C': 'Biopsy',
  'option_D': 'Blood test',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0027',
  'question_type': 'Modality Recognition',
  'question': 'What method was employed to obtain this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im176_ACRIMA.png',
  'option_A': 'CT scan',
  'option_B': 'Blood test',
  'option_C': 'Fundus imaging',
  'option_D': 'X-ray',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0028',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was utilized to acquire this picture?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im486_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'PET scan',
  'option_C': 'Ultrasound',
  'option_D': 'CT scan',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0029',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im603_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'Electroencephalogram (EEG)',
  'option_C': 'PET scan',
  'option_D': 'Electrocardiogram (ECG)',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0030',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im248_ACRIMA.png',
  'option_A': 'Blood test',
  'option_B': 'Fundus imaging',
  'option_C': 'MRI',
  'option_D': 'PET scan',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0031',
  'question_type': 'Modality Recognition',
  'question': 'Which imaging technique was utilized to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im332_g_ACRIMA.png',
  'option_A': 'Ultrasound',
  'option_B': 'Fundus imaging',
  'option_C': 'Electrocardiogram (ECG)',
  'option_D': 'PET scan',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0032',
  'question_type': 'Modality Recognition',
  'question': 'What imaging technique was employed to acquire this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im477_g_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'CT scan',
  'option_C': 'Blood test',
  'option_D': 'MRI',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0033',
  'question_type': 'Modality Recognition',
  'question': 'What modality was used to capture this image?',
  'gt_answer': 'Fundus imaging',
  'image_path': 'Images/ACRIMA/Im262_ACRIMA.png',
  'option_A': 'Fundus imaging',
  'option_B': 'Ultrasound',
  'option_C': 'MRI',
  'option_D': 'X-ray',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0034',
  'question_type': 'Disease Diagnosis',
  'question': 'Is there anything abnormal or evidence of glaucoma in the eyes in this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im041_ACRIMA.png',
  'option_A': 'Optic nerve damage noted',
  'option_B': 'Conjunctivitis diagnosed',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Cataracts present',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0035',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im015_ACRIMA.png',
  'option_A': 'Myopia positive',
  'option_B': 'Corneal ulcer identified',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Astigmatism detected',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0036',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im056_ACRIMA.png',
  'option_A': 'Astigmatism detected',
  'option_B': 'Macular degeneration evident',
  'option_C': 'Optic nerve damage noted',
  'option_D': "It's normal, glaucoma negative",
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0037',
  'question_type': 'Disease Diagnosis',
  'question': 'Is the condition of the eyes in this image normal or does it show any sign of glaucoma?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im009_ACRIMA.png',
  'option_A': 'Astigmatism detected',
  'option_B': 'Macular degeneration evident',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Age-related macular degeneration diagnosed',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0038',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im086_ACRIMA.png',
  'option_A': 'Retinal detachment confirmed',
  'option_B': "It's normal, glaucoma negative",
  'option_C': 'Macular degeneration evident',
  'option_D': 'Color blindness confirmed',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0039',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im080_ACRIMA.png',
  'option_A': 'Retinal detachment confirmed',
  'option_B': 'Corneal ulcer identified',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Astigmatism detected',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0040',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im076_ACRIMA.png',
  'option_A': 'Conjunctivitis diagnosed',
  'option_B': 'Macular degeneration evident',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Optic nerve damage noted',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0041',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im163_ACRIMA.png',
  'option_A': 'Age-related macular degeneration diagnosed',
  'option_B': 'Macular degeneration evident',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Cataracts present',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0042',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im032_ACRIMA.png',
  'option_A': 'Astigmatism detected',
  'option_B': 'Retinal detachment confirmed',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Cataracts present',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0043',
  'question_type': 'Disease Diagnosis',
  'question': 'Is there any abnormality or presence of glaucoma in the eyes in this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im212_ACRIMA.png',
  'option_A': "It's normal, glaucoma negative",
  'option_B': 'Color blindness confirmed',
  'option_C': 'Conjunctivitis diagnosed',
  'option_D': 'Retinal detachment confirmed',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0044',
  'question_type': 'Disease Diagnosis',
  'question': 'What is the condition of the eyes in  this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im230_ACRIMA.png',
  'option_A': 'Retinal detachment confirmed',
  'option_B': "It's normal, glaucoma negative",
  'option_C': 'Conjunctivitis diagnosed',
  'option_D': 'Corneal ulcer identified',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0045',
  'question_type': 'Disease Diagnosis',
  'question': 'Is there any abnormality or presence of glaucoma in the eyes in this image?',
  'gt_answer': "It's normal, glaucoma negative",
  'image_path': 'Images/ACRIMA/Im002_ACRIMA.png',
  'option_A': 'Myopia positive',
  'option_B': 'Conjunctivitis diagnosed',
  'option_C': "It's normal, glaucoma negative",
  'option_D': 'Retinal detachment confirmed',
  'modality_type': 'Fundus Photography'},
 {'dataset': 'ACRIMA',
  'question_id': 'ACRIMA_0046',

In [62]:
unique_image_path_l = np.unique([x["image_path"] for x in data_all])
len(unique_image_path_l)

82059

In [63]:
len(data_all)

88996

In [64]:
np.random.shuffle(unique_image_path_l)
# sample 10%
unique_image_path_l = unique_image_path_l[: int(len(unique_image_path_l) * 0.1)]

train_image_l = unique_image_path_l[: int(len(unique_image_path_l) * 0.3)]
test_image_l = unique_image_path_l[int(len(unique_image_path_l) * 0.3) :]

In [65]:
len(unique_image_path_l)

8205

In [66]:
from tqdm import tqdm

datasets = np.unique([x["dataset"] for x in data_all])
split_summary = {}
for dataset in datasets:
    split_summary[dataset] = {"question_train": 0, "question_test": 0}

train_json_l = []
test_json_l = []

for item in tqdm(data_all):
    item_ = {
        "question_id": item["question_id"],
        "dataset": item["dataset"],
        "image_path": item["image_path"],
        "access_type": "Open-access",
    }

    if item["image_path"] in train_image_l:
        train_json_l.append(item_)
        split_summary[item["dataset"]]["question_train"] += 1
    elif item["image_path"] in test_image_l:
        test_json_l.append(item_)
        split_summary[item["dataset"]]["question_test"] += 1

df_split_summary = pd.DataFrame(split_summary)
df_split_summary

  1%|▏         | 1305/88996 [00:00<00:13, 6532.88it/s]

100%|██████████| 88996/88996 [00:22<00:00, 4011.80it/s]

,ACRIMA,ALL Challenge,Adam Challenge,BioMediTech,Blood Cell,BreakHis,COVIDx CXR-4,CRC100k,Chest CT Scan,Chest X-Ray PA,...,OLIVES,PAD-UFES-20,PALM2019,Pulmonary Chest MC,Pulmonary Chest Shenzhen,RUS CHN,RadImageNet,Retinal OCT-C8,SARS-CoV-2 CT-scan,Yangxi
question_train,10,5,2,18,27,21,16,54,26,26,...,22,17,18,0,1,58,1691,140,29,46
question_test,10,32,10,38,64,52,34,84,54,55,...,47,32,28,1,17,141,3925,273,59,110

In [67]:
df_split_summary_ = df_split_summary.T
df_split_summary_["dataset"] = df_split_summary_.index
df_split_summary_ = df_split_summary_.reset_index(drop=True)[["dataset", "question_train", "question_test"]]
df_split_summary_

                      dataset  question_train  question_test
0                      ACRIMA              10             10
1               ALL Challenge               5             32
2              Adam Challenge               2             10
3                 BioMediTech              18             38
4                  Blood Cell              27             64
5                    BreakHis              21             52
6                COVIDx CXR-4              16             34
7                     CRC100k              54             84
8               Chest CT Scan              26             54
9              Chest X-Ray PA              26             55
10                 CoronaHack              11             56
11                   Covid CT               6             20
12           Covid-19 tianchi               5              4
13           Covid19 heywhale              24             59
14                     DRIMDB               8              9
15                   DeepDRiD               6             12
16       Diabetic Retinopathy              49            144
17            Fitzpatrick 17k              39            106
18                     HuSHeM               5              7
19                   ISBI2016              18             37
20                   ISIC2018               3             16
21                   ISIC2019              61            159
22                   ISIC2020              51            115
23                      JSIEC               6             19
24        Knee Osteoarthritis              18             45
25                MAlig Lymph               2             10
26                      MHSMA              42             95
27                       MIAS               6              6
28  Monkeypox Skin Image 2022               7              6
29                       Mura              38             97
30          NLM- Malaria Data               3              6
31           OCT & X-Ray 2017              42             92
32                     OLIVES              22             47
33                PAD-UFES-20              17             32
34                   PALM2019              18             28
35         Pulmonary Chest MC               0              1
36   Pulmonary Chest Shenzhen               1             17
37                    RUS CHN              58            141
38                RadImageNet            1691           3925
39             Retinal OCT-C8             140            273
40         SARS-CoV-2 CT-scan              29             59
41                     Yangxi              46            110

In [68]:
def save_jsonl(data, filepath):
    with open(filepath, "w", encoding="utf-8") as f:
        for item in data:
            json_line = json.dumps(item, ensure_ascii=False)
            f.write(json_line + "\n")


df_split_summary_.to_csv(os.path.join(
    root, "data_split_summary.csv"), index=False)

save_jsonl(train_json_l, os.path.join(root, "omnimedvqa_train_index.jsonl"))
save_jsonl(test_json_l, os.path.join(root, "omnimedvqa_test_index.jsonl"))

In [ ]:
{
    "question_id": "RadImageNet_33584",
    "dataset": "RadImageNet",
    "image_path": "Images/RadImageNet/chondral_abnormality/foot051933.png",
    "access_type": "Open-access",
}